### ISSUE TITLE
Discussion: DWM

### ISSUE THREAD

**Issue by mitchweaver** [mitchweaver/suckless#2]

**Comment by bluedrack** [comment]
I see that you have made a dwm where the border a round. Can you explain me how you did that ?

**Comment by mitchweaver** [comment]
@Bluedrack28 https://github.com/MitchWeaver/suckless/blob/cc376c654a30aed4d2bd7d627f07b2c21acdc03c/dwm/dwm.c#L963
As you can see it is commented out as its quite slow, at least on my x200 anyway

It could surely be optimized but it does look nice. I don't usually use it.

Here's another picture of it: http://ix.io/1PKq.png

**Comment by bluedrack** [comment]
Thank you for responding so quickly. I will take a look and see if I have the same performance issue.
But thank you really much I'm looking for this feature for so long. I will see if I can make some improvements.

**Comment by mitchweaver** [comment]
@Bluedrack28 BTW: you're going to need to call this every time a client is re-rendered, just do a ^C-f search on the function name to find every instance its needed, possibly in the other .c files too I don't remember.

**Comment by bluedrack** [comment]
Ok, i tried to make it work for me. But I don't have succed to install it. They are dependences that I don't have I, I can't make it work. But thanks, maybe one day I will have round corner in my desktop.

**Comment by mitchweaver** [comment]
@Bluedrack28  If you give compiler output I could try and deduce which libs you're missing.

**Comment by bluedrack** [comment]
I realized the cause of the problem. It was the compiler, I had not tcc on my machine. With gcc, it works perfectly. I will try to make a .diff later.

**Comment by Error916** [comment]
in one reddit post i found you made your own fifo can you explain how you did it, link your all dwm folder or make a patch for it? I would be greatfull

**Comment by mitchweaver** [comment]
@Error916 oh man that is ANCIENT... It's probably lost to time... I've since stopped using lemonbar and now the images you see are actually DWM's native bar.

I did it hacking with this patch here: https://dwm.suckless.org/patches/dwmfifo

You might be able to still find the code in first dozen or so commits of this repo but beware the code is *terrible*... And it was before I had the build/patch system so it'll be hard to navigate/understand

**Comment by Error916** [comment]
tx for the fast replay, i try that patch but make dwm crash and i dont know how to get the workspace number for lemonbar ahahha. I will try to search in your commits

**Comment by samarthkulshrestha** [comment]
When i run ./build.sh dwm, there is an error saying:
/usr/include/X11/Xft/Xft.h:39:10: fatal error: ft2build.h: No such file or directory
   39 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: drw.o] Error 1

**Comment by mitchweaver** [comment]
> ft2build.h: No such file or directory

You're missing freetype2 headers. @Samarth2005

**Comment by slymealien** [comment]
Great work ,I  love this setup.
How to enable window names/titles in menubar ?

**Comment by mitchweaver** [comment]
> Great work ,I love this setup.
> How to enable window names/titles in menubar ?

This is the `dwm-17-notitle` patch, just remove the patch if you wish.

**Comment by pavan-tx9** [comment]
Hi, was wondering when I try to run ./build.sh on any of these suckless tools it says missing <dwm.h> or <st.h>, no such file or directory. I must be missing something but not sure, could you let me know? Thanks.

**Comment by mitchweaver** [comment]
@s9chroma read the comment that is in every config.h file:

```c
  // theme, included from ${HOME}/.cache/themes in config.mk
#include <dwm.h>
```

**Comment by pavan-tx9** [comment]
Hey thanks for the reply, I did get to that but couldn't figure out where to get the header file from...I mean currently my ${HOME}/.cache/themes is empty

**Comment by mitchweaver** [comment]
@s9chroma Yeah it's not default to dwm/st/etc. These are themes I create. It's just an easy method of switching themes. You can create your own and either put it there, or symlink to there, and have it included.

**Comment by pavan-tx9** [comment]
Oh ok so do you create dwm/st headers inside the  ${HOME}/.cache/themes folder and have a colors array in them?

**Comment by mitchweaver** [comment]
@s9chroma https://github.com/mitchweaver/bin/blob/master/rice

**Comment by pavan-tx9** [comment]
Thanks!

**Comment by 20jam** [comment]
Hay thanks for those great patches, I've tried to patch my dwm with rounded corners however I failled:

```
$ patch -p1 < ./patches/mitch-06-rounded_corners-f087d20e6e60a49c756936b4312f5d194d8e63b4.patch

patching file dwm.c
Hunk #2 FAILED at 242.
Hunk #3 succeeded at 1073 (offset -61 lines).
Hunk #4 succeeded at 1291 (offset -50 lines).
Hunk #5 FAILED at 1446.
Hunk #6 succeeded at 1395 (offset -64 lines).
2 out of 6 hunks FAILED -- saving rejects to file dwm.c.rej
zsh: exit 1     patch -p1 <
```

Can you please look into it, or tell me kindly if I'm missing a step .

Thanks

**Comment by tamibam** [comment]
> /* 1. You need to add '-lXext' to the libraries linked in config.mk */
> /*               LIBS = -L${X11LIB} -lX11 -lXext */

```
usr/bin/ld: cannot find -lxext
```
Is this some sort of library need installing, Thanks

**Comment by mitchweaver** [comment]
Rounded corners isn't maintained. If patches fail you need to correct the hunks manually.

**Comment by edcsnt** [comment]
I downloaded dwm-6.2, applied all the active patches sequentially, correcting the failed hunks, copied config.h and config.mk, but still got tons of error during compilation: https://pastebin.com/raw/6SCLUTmk

Any ideas?

**Comment by mitchweaver** [comment]
@wardo0  Most of those are warnings, the error that's breaking compilation is: `error: ‘colors’ undeclared`

It looks like you have the same issue at the other commenter a few comments above
