### ISSUE TITLE
Discussion: ST

### ISSUE THREAD

**Issue by mitchweaver** [mitchweaver/suckless#4]
For general discussion on `st` hacking, patches, and troubleshooting.

**Comment by kiedtl** [comment]
Just a heads-up... st scrollback patch need to be fixed due to recent commits in upstream st repository.

**Comment by aaaaaaaalex** [comment]
Hey, I'm very very new to your tools and a newb C programmer but...

Building with `./build.sh st` appears to be broken on [HEAD->master](https://github.com/mitchweaver/suckless/commit/f05fd5d03c5efa5a0d1dc2ac4e37c32cb294b103) currently.
It's failing for me with the error:
```
In file included from x.c:65:
config.h:39:10: fatal error: st.h: No such file or directory
   39 | #include <st.h>

```

I would assume I just messed something up or was missing a dep, only that I can manually build st suc(k)cessfully:
```
git clone https://git.suckless.org/st
cd st
make clean install
```

Thanks :smile: 
A.

**Comment by mitchweaver** [comment]
@aaaaaaaalex  Read the comment above where that file is being included in st's `config.h`:

```
// theme, included from ${HOME}/.cache/themes in config.mk
#include <st.h>
```

This is where you would paste in whatever theme you want to use, or if you want to use my setup, see how I generate suckless themes based on color palettes in the script [rice](https://github.com/mitchweaver/bin/blob/master/rice/rice) from my bin repo
